### ISSUE TITLE
Hello! I got an IndexError: tuple index out of range error when I tried to use your code soundnet_localize_sound_source to  reproduce it, how can I solve this problem?

### ISSUE THREAD

**Issue by Yuki-jy** [liyidi/soundnet_localize_sound_source#1]
runcell(0, 'C:/Users/Administrator/Downloads/soundnet_localize_sound_source-main/mytest_avnet.py')
Eval step: 0 ('D:/PROJECT/soundnet_localize_sound_source-main/mydata/10602295346\n',)
Traceback (most recent call last):
 
  File "C:\Users\Administrator\Downloads\soundnet_localize_sound_source-main\mytest_avnet.py", line 31, in <module>
    image_map = unloader(norm_image)
 
  File "D:\ana\lib\site-packages\torchvision\transforms\transforms.py", line 110, in __call__
    return F.to_pil_image(pic, self.mode)
 
  File "D:\ana\lib\site-packages\torchvision\transforms\functional.py", line 115, in to_pil_image
    if npimg.shape[2] == 1:
 
IndexError: tuple index out of range

**Comment by liyidi** [comment]
> runcell(0, 'C:/Users/Administrator/Downloads/soundnet_localize_sound_source-main/mytest_avnet.py')
> Eval step: 0 ('D:/PROJECT/soundnet_localize_sound_source-main/mydata/10602295346\n',)
> Traceback (most recent call last):
> 
> File "C:\Users\Administrator\Downloads\soundnet_localize_sound_source-main\mytest_avnet.py", line 31, in
> image_map = unloader(norm_image)
> 
> File "D:\ana\lib\site-packages\torchvision\transforms\transforms.py", line 110, in **call**
> return F.to_pil_image(pic, self.mode)
> 
> File "D:\ana\lib\site-packages\torchvision\transforms\functional.py", line 115, in to_pil_image
> if npimg.shape[2] == 1:
> 
> IndexError: tuple index out of range

@Yuki-jy 
My torchvision's version is 0.7.0, cv2's version is 4.4.0, python 3.6.12. I didn't meet this IndexError.
Please check your package's version.

**Comment by Yuki-jy** [comment]
Thanks! I found my torchvision's version is 0.2.1, cv2's version is  4.0.1, python  3.8.5. You mean there is some problem with my torchvision , opencv or pyhton 's version? Could you please give me some advice?

**Comment by liyidi** [comment]
> Thanks! I found my torchvision's version is 0.2.1, cv2's version is 4.0.1, python 3.8.5. You mean there is some problem with my torchvision , opencv or pyhton 's version? Could you please give me some advice?

The error occurs in the function of torchvision, probably because the version of torchvision is too low. I suggest you upgrade the package.

**Comment by Yuki-jy** [comment]
Thank You. I have solved the issue by updating torchvision's version.
